// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiMuM9QKajy8Pq4X8JUKKziAOsJ62UuNs',
    appId: '1:893194704916:web:10d52b74a17636b3776f01',
    messagingSenderId: '893194704916',
    projectId: 'note-b0a2f',
    authDomain: 'note-b0a2f.firebaseapp.com',
    storageBucket: 'note-b0a2f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOkJ37gyJLd_cARisSr9Wq8zQMSrXbuzg',
    appId: '1:893194704916:android:0bbda9efe82671b2776f01',
    messagingSenderId: '893194704916',
    projectId: 'note-b0a2f',
    storageBucket: 'note-b0a2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd-j3F03vFRBEd9c5O7wO9pEiNunWtAR8',
    appId: '1:893194704916:ios:e983f121d0f3bc61776f01',
    messagingSenderId: '893194704916',
    projectId: 'note-b0a2f',
    storageBucket: 'note-b0a2f.firebasestorage.app',
    iosBundleId: 'com.yourname.noteKeepApp',
  );

}